kind: Service
apiVersion: v1
metadata:
  name: helidon-mp
  labels:
    app: helidon-mp
spec:
  type: NodePort
  selector:
    app: helidon-mp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helidon-mp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helidon-mp
        version: v1
    spec:
      containers:
      - name: helidon-mp
        image: helidon-mp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
