DROP TABLE IF EXISTS GREETING;

CREATE TABLE GREETING (
    ID IDENTITY PRIMARY KEY,
    SALUTATION VARCHAR(64) NOT NULL,
    RESPONSE VARCHAR(64) NOT NULL
);

INSERT INTO GREETING (SALUTATION, RESPONSE) VALUES ('Aloha', 'Ciao');